### ISSUE TITLE
Cannot find module `html-validator`

### ISSUE THREAD

**Issue by alallier** [kethinov/roosevelt#91]
Just upgraded to latest Roosevelt (`0.7.3`) and am receiving this error:

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'html-validator'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (J:\My Documents\something\node_modules\roosevelt\lib\htmlValidator.js:2:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Program node app.js -prod exited with code 1
```

**Comment by kethinov** [comment]
re-run `npm i`

**Comment by alallier** [comment]
I did still no luck.

**Comment by kethinov** [comment]
this should fix it https://github.com/kethinov/roosevelt/commit/866151947d13eb168027dd634530af1348e03bb5

**Comment by alallier** [comment]
Ah yes nice catch, thank you!
